// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEOrKvHiw9rm8diCUcAmleR3JS4duOPnw',
    appId: '1:532432873470:web:e4e19f8981bcfcea0282af',
    messagingSenderId: '532432873470',
    projectId: 'el-prof-de416',
    authDomain: 'el-prof-de416.firebaseapp.com',
    storageBucket: 'el-prof-de416.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBazXXGcSeJCm3vRJL4aIQ36w-NnkEyotY',
    appId: '1:532432873470:android:62d0d4d05eca47120282af',
    messagingSenderId: '532432873470',
    projectId: 'el-prof-de416',
    storageBucket: 'el-prof-de416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj2ggR1M2DSmAdVHWi5LJpAr2OQkrq1hs',
    appId: '1:532432873470:ios:44ef0cd49808c7720282af',
    messagingSenderId: '532432873470',
    projectId: 'el-prof-de416',
    storageBucket: 'el-prof-de416.appspot.com',
    iosBundleId: 'com.prof.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj2ggR1M2DSmAdVHWi5LJpAr2OQkrq1hs',
    appId: '1:532432873470:ios:44ef0cd49808c7720282af',
    messagingSenderId: '532432873470',
    projectId: 'el-prof-de416',
    storageBucket: 'el-prof-de416.appspot.com',
    iosBundleId: 'com.prof.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEOrKvHiw9rm8diCUcAmleR3JS4duOPnw',
    appId: '1:532432873470:web:db7bdf65d9fd85ee0282af',
    messagingSenderId: '532432873470',
    projectId: 'el-prof-de416',
    authDomain: 'el-prof-de416.firebaseapp.com',
    storageBucket: 'el-prof-de416.appspot.com',
  );
}
